----
title: "Comparing Maps: Some examples with the island of La Réunion"
author: "Julien Jamme"
date: "2023-04-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = file.path(getwd(),".."))
```


## Objectives

- How does the KWD measure react to different types of maps to compare ?
- How different from a standard measure is the KWD when comparing maps ?

```{r}
if(! "SpatialKWD" %in% installed.packages()[,1]) install.packages("SpatialKWD")

library(raster)
library(btb)
library(ggplot2)
library(purrr)
library(dplyr)
library(SpatialKWD)


source("R/functions.R", encoding = "UTF-8")
```

```{r}
# download.file("https://www.insee.fr/fr/statistiques/fichier/6215140/Filosofi2017_carreaux_1km_gpkg.zip", "filo2017_1km_gpkg.zip")
reunion <- sf::st_read("data/Filosofi2017_carreaux_1km_reun.gpkg")
str(reunion)
```

```{r}
reunion_coords <- from_INSPIRE_to_xy(reunion$Idcar_1km, crs = "2975", res = "1000m")
str(reunion_coords)
```

```{r}
set.seed(1234)
reunion_df <- reunion %>% 
  sf::st_drop_geometry() %>% 
  dplyr::bind_cols(as.data.frame(reunion_coords)) %>% 
  dplyr::select(Idcar_1km, x,y,Ind,Men_pauv)

reunion_df_sm_2km <- reunion_df %>% dplyr::select(-1) %>% 
  btb::btb_smooth(sEPSG = "2975", iCellSize = 1000, iBandwidth = 2000) %>% 
  rename_with(~paste0(.,"_sm2km"), c("Ind","Men_pauv"))
reunion_df_sm_5km <- reunion_df %>% dplyr::select(-1) %>% 
  btb::btb_smooth(sEPSG = "2975", iCellSize = 1000, iBandwidth = 5000) %>% 
  rename_with(~paste0(.,"_sm5km"), c("Ind","Men_pauv"))
reunion_df_sm_10km <- reunion_df %>% dplyr::select(-1) %>% 
  btb::btb_smooth(sEPSG = "2975", iCellSize = 1000, iBandwidth = 10000, inspire = TRUE) %>% 
  rename_with(~paste0(.,"_sm10km"), c("Ind","Men_pauv"))

reunion_sf <- reunion_df_sm_2km %>% sf::st_drop_geometry() %>%  
  full_join(reunion_df_sm_5km %>% sf::st_drop_geometry(), by = c("x","y")) %>% 
  full_join(reunion_df_sm_10km, by = c("x","y")) %>% 
  sf::st_as_sf() %>% 
  full_join(
  reunion_df %>% dplyr::select(-x,-y) %>% 
    mutate(across(.cols = Ind:Men_pauv, ~sample(.), .names = "{.col}_perm")),
  by = c("idInspire" = "Idcar_1km")
  ) %>% 
  mutate(across(matches("(^Ind|^Men)", perl = TRUE), ~ifelse(is.na(.), 0, .)))%>% 
  dplyr::relocate(Ind, Men_pauv, .after = y)

plot(reunion_sf %>% sf::st_geometry())
summary(reunion_sf)
reunion_sf %>% str()
```

## Working on a regional map 

```{r}
reunion_raster_Ind <- rasterFromXYZ(
  xyz = reunion_sf %>% sf::st_drop_geometry() %>% dplyr::select(x,y,starts_with("Ind")) %>% 
    arrange(x,y)
)
reunion_raster_Ind[is.na(reunion_raster_Ind)] <- 0
plot(reunion_raster_Ind)
```
Remark: typical case where the map is full of empty cells.


```{r}
kwd_reunion_ind <- compareOneToMany(
  reunion_raster_Ind %>% coordinates(), 
  reunion_raster_Ind %>% values(), 
  recode = TRUE
)
kwd_reunion_ind$distance
```

```{r}
hell_reunion_ind <- hellinger(
  reunion_raster_Ind %>% values()
)
hell_reunion_ind
```

```{r}
rmse_reunion_ind <- rmse(
  reunion_raster_Ind %>% values()
)
rmse_reunion_ind
```

```{r}
tibble(
  map = c("smooth_2km","smooth_5km","smooth_10km", "perm_alea"),
  kwd = kwd_reunion_ind$distance,
  hellinger = hell_reunion_ind,
  rmse = rmse_reunion_ind
)
```


## Working with a city map


```{r}
st_louis_centroide <- sf::st_as_sf(
  # data.frame(x=c(333310,339601),y=c(7644145,7649149)), coords = c("x","y"), crs = 2975) %>% 
  data.frame(x=337100,y=7646600), coords = c("x","y"), crs = 2975) %>% 
  sf::st_as_sfc()

buffer <- sf::st_buffer(st_louis_centroide, dist = 10000,endCapStyle = "SQUARE")
```

```{r}
inter_buffer <- sf::st_within(
  reunion_sf, buffer
)
st_louis_area <- reunion_sf %>% filter(lengths(inter_buffer)>0)
nrow(st_louis_area)
```

```{r}
st_louis_raster_Ind <- rasterFromXYZ(
  xyz = st_louis_area %>% sf::st_drop_geometry() %>% dplyr::select(x,y,starts_with("Ind")) %>% 
    arrange(x,y)
)
st_louis_raster_Ind[is.na(st_louis_raster_Ind)] <- 0
plot(st_louis_raster_Ind)
```


```{r}
kwd_st_louis_ind <- compareOneToMany(
  st_louis_raster_Ind %>% coordinates(), 
  st_louis_raster_Ind %>% values(), 
  recode = TRUE
)
kwd_st_louis_ind$distance
```

```{r}
hell_st_louis_ind <- hellinger(
  st_louis_raster_Ind %>% values()
)
hell_st_louis_ind
```

```{r}
rmse_st_louis_ind <- rmse(
  st_louis_raster_Ind %>% values()
)
rmse_st_louis_ind
```

```{r}
tibble(
  map = c("smooth_2km","smooth_5km","smooth_10km", "perm_alea"),
  kwd = kwd_st_louis_ind$distance,
  hellinger = hell_st_louis_ind,
  rmse = rmse_st_louis_ind
)
```
